# Generated by Django 3.1.3 on 2023-04-14 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_rename_status_name_statuscrm_status_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statuscrm',
            old_name='status_name',
            new_name='Status_name',
        ),
    ]
